version: '3.8'
services:   
  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq      
    volumes: 
          - ./definitionsv2.json:/etc/rabbitmq/definitions.json       
    ports: 
          - "15672:15672"
          - "5672:5672"       
    environment:
                -RABBITMQ_DEFAULT_USER=admin
                -RABBITMQ_DEFAULT_PASS=admin